// inertia/pages/auth/register.tsx
import { Head, Link } from '@inertiajs/react'
import { motion } from 'motion/react'
import {
  EnvelopeIcon,
  LockClosedIcon,
  UserIcon,
  MapPinIcon,
  PhoneIcon,
  CalendarIcon,
} from '@heroicons/react/24/outline'
import AuthLayout from '~/components/layouts/AuthLayout'
import Input from '~/components/ui/Input'
import Select from '~/components/ui/Select'
import Button from '~/components/ui/Button'
import { useValidatedForm } from '~/hooks/useValidatedForm'
import { registerSchema } from '~/lib/validation'
import { useRouteGuard } from '~/hooks/useRouteGuard'
import { PROVINCES } from '~/lib/constants'

export default function Register() {
  useRouteGuard({ requiresGuest: true })

  const { form, getError, handleBlur, submit, shouldShowError } = useValidatedForm({
    schema: registerSchema,
    initialData: {
      firstName: '',
      lastName: '',
      email: '',
      password: '',
      password_confirmation: '',
      age: '',
      province: '',
      commune: '',
      phoneNumber: '',
    },
  })

  const provinceOptions = PROVINCES.map((p) => ({
    value: p,
    label: p,
  }))

  const handleSubmit = async () => {
    await submit('post', '/auth/register')
  }

  return (
    <>
      <Head title="Inscription" />
      <AuthLayout>
        <motion.div
          className="w-full max-w-3xl"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4, delay: 0.1 }}
        >
          <div className="bg-white/90 backdrop-blur-xl rounded-3xl shadow-2xl border border-white/50 p-8 md:p-10">
            {/* Header */}
            <motion.div
              className="text-center mb-8"
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: 0.2 }}
            >
              <h1 className="text-3xl font-bold text-neutral-900 mb-2">Créer un compte</h1>
              <p className="text-neutral-600">Rejoignez notre communauté d'événements</p>
            </motion.div>

            {/* Form */}
            <div className="space-y-6">
              {/* Name Fields */}
              <motion.div
                className="grid grid-cols-1 md:grid-cols-2 gap-4"
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.4, delay: 0.3 }}
              >
                <Input
                  label="Prénom"
                  type="text"
                  value={form.data.firstName}
                  onChange={(value) => form.setData('firstName', value as string)}
                  onBlur={() => handleBlur('firstName')}
                  error={shouldShowError('firstName') ? getError('firstName') : undefined}
                  icon={UserIcon}
                  placeholder="Jean"
                  required
                  disabled={form.processing}
                />
                <Input
                  label="Nom"
                  type="text"
                  value={form.data.lastName}
                  onChange={(value) => form.setData('lastName', value as string)}
                  onBlur={() => handleBlur('lastName')}
                  error={shouldShowError('lastName') ? getError('lastName') : undefined}
                  icon={UserIcon}
                  placeholder="Dupont"
                  required
                  disabled={form.processing}
                />
              </motion.div>

              {/* Email */}
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.4, delay: 0.4 }}
              >
                <Input
                  label="Adresse email"
                  type="email"
                  value={form.data.email}
                  onChange={(value) => form.setData('email', value as string)}
                  onBlur={() => handleBlur('email')}
                  error={shouldShowError('email') ? getError('email') : undefined}
                  icon={EnvelopeIcon}
                  placeholder="votre.email@exemple.com"
                  required
                  disabled={form.processing}
                />
              </motion.div>

              {/* Password Fields */}
              <motion.div
                className="grid grid-cols-1 md:grid-cols-2 gap-4"
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.4, delay: 0.5 }}
              >
                <Input
                  label="Mot de passe"
                  type="password"
                  value={form.data.password}
                  onChange={(value) => form.setData('password', value as string)}
                  onBlur={() => handleBlur('password')}
                  error={shouldShowError('password') ? getError('password') : undefined}
                  icon={LockClosedIcon}
                  placeholder="••••••••"
                  required
                  hint="Au moins 8 caractères"
                  disabled={form.processing}
                />
                <Input
                  label="Confirmer le mot de passe"
                  type="password"
                  value={form.data.password_confirmation}
                  onChange={(value) => form.setData('password_confirmation', value as string)}
                  onBlur={() => handleBlur('password_confirmation')}
                  error={
                    shouldShowError('password_confirmation')
                      ? getError('password_confirmation')
                      : undefined
                  }
                  icon={LockClosedIcon}
                  placeholder="••••••••"
                  required
                  disabled={form.processing}
                />
              </motion.div>

              {/* Age */}
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.4, delay: 0.6 }}
              >
                <Input
                  label="Âge"
                  type="number"
                  value={form.data.age}
                  onChange={(value) => form.setData('age', value)}
                  onBlur={() => handleBlur('age')}
                  error={shouldShowError('age') ? getError('age') : undefined}
                  icon={CalendarIcon}
                  placeholder="25"
                  required
                  min={13}
                  max={120}
                  disabled={form.processing}
                />
              </motion.div>

              {/* Location Fields */}
              <motion.div
                className="grid grid-cols-1 md:grid-cols-2 gap-4"
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.4, delay: 0.7 }}
              >
                <Select
                  label="Wilaya"
                  value={form.data.province}
                  onChange={(value) => form.setData('province', value as string)}
                  options={provinceOptions}
                  placeholder="Sélectionnez une wilaya"
                  error={shouldShowError('province') ? getError('province') : undefined}
                  required
                  searchable
                  disabled={form.processing}
                />
                <Input
                  label="Commune"
                  type="text"
                  value={form.data.commune}
                  onChange={(value) => form.setData('commune', value as string)}
                  onBlur={() => handleBlur('commune')}
                  error={shouldShowError('commune') ? getError('commune') : undefined}
                  icon={MapPinIcon}
                  placeholder="Ex: Bab Ezzouar"
                  required
                  disabled={form.processing}
                />
              </motion.div>

              {/* Phone Number */}
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.4, delay: 0.8 }}
              >
                <Input
                  label="Numéro de téléphone"
                  type="tel"
                  value={form.data.phoneNumber}
                  onChange={(value) => form.setData('phoneNumber', value as string)}
                  onBlur={() => handleBlur('phoneNumber')}
                  error={shouldShowError('phoneNumber') ? getError('phoneNumber') : undefined}
                  icon={PhoneIcon}
                  placeholder="+213 555 123 456"
                  hint="Optionnel"
                  disabled={form.processing}
                />
              </motion.div>

              {/* Submit Button */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.4, delay: 0.9 }}
              >
                <Button
                  variant="gradient"
                  size="lg"
                  fullWidth
                  loading={form.processing}
                  disabled={form.processing}
                  onClick={handleSubmit}
                >
                  Créer mon compte
                </Button>
              </motion.div>

              {/* Login Link */}
              <motion.div
                className="text-center pt-4 border-t border-neutral-200"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.4, delay: 1.0 }}
              >
                <p className="text-sm text-neutral-600">
                  Vous avez déjà un compte ?{' '}
                  <Link
                    href="/auth/login"
                    className="font-semibold text-primary-600 hover:text-primary-700 transition-colors"
                  >
                    Se connecter
                  </Link>
                </p>
              </motion.div>
            </div>
          </div>

          {/* Additional Info */}
          <motion.div
            className="mt-6 text-center"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.4, delay: 1.1 }}
          >
            <p className="text-xs text-neutral-500">
              En créant un compte, vous acceptez nos{' '}
              <a href="#" className="text-primary-600 hover:underline">
                Conditions d'utilisation
              </a>{' '}
              et notre{' '}
              <a href="#" className="text-primary-600 hover:underline">
                Politique de confidentialité
              </a>
            </p>
          </motion.div>
        </motion.div>
      </AuthLayout>
    </>
  )
}

// inertia/pages/auth/register.vue
<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3'
import { UserIcon, EnvelopeIcon, LockClosedIcon, PhoneIcon } from '@heroicons/vue/24/outline'
import AuthLayout from '~/components/layouts/AuthLayout'
import Input from '#ui/Input.vue'
import Select from '#ui/Select.vue'
import Button from '#ui/Button.vue'
import { use_vlidated_form } from '~/composables/use_validated_form'
import { registerSchema } from '~/lib/validation'
import { PROVINCES } from '~/lib/constants'

const { form, getError, validateField, validateAll, clearError } = use_vlidated_form(
  registerSchema,
  {
    firstName: '',
    lastName: '',
    email: '',
    password: '',
    password_confirmation: '',
    age: '',
    province: '',
    commune: '',
    phoneNumber: '',
  }
)

const provinceOptions = PROVINCES.map((p) => ({ value: p, label: p }))

const handleSubmit = async () => {
  const isValid = await validateAll()
  if (!isValid) return

  form.post('/auth/register', {
    preserveScroll: true,
  })
}

const handleBlur = (field: keyof typeof form.data) => {
  validateField(field)
}
</script>

<template>
  <Head>
    <title>Inscription - Créez votre compte</title>
    <meta
      name="description"
      content="Créez votre compte gratuitement pour découvrir et vous inscrire aux meilleurs événements près de chez vous."
    />
    <meta name="robots" content="noindex, nofollow" />
  </Head>

  <AuthLayout>
    <div
      class="w-full max-w-2xl"
      v-motion
      :initial="{ opacity: 0, y: 20 }"
      :enter="{ opacity: 1, y: 0, transition: { duration: 400 } }"
    >
      <!-- Header -->
      <header class="text-center mb-8">
        <h1 class="text-3xl font-bold text-sand-12 mb-2">Créez votre compte</h1>
        <p class="text-sand-11">Rejoignez notre communauté d'événements</p>
      </header>

      <!-- Form Card -->
      <section
        class="bg-white shadow-xl rounded-2xl p-8 border border-sand-6"
        aria-label="Formulaire d'inscription"
      >
        <form @submit.prevent="handleSubmit" class="space-y-6" novalidate>
          <!-- Name Fields -->
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Input
              v-model="form.firstName"
              type="text"
              label="Prénom"
              placeholder="Jean"
              :icon="UserIcon"
              :error="getError('firstName')"
              required
              autocomplete="given-name"
              @blur="handleBlur('firstName')"
              @input="clearError('firstName')"
            />

            <Input
              v-model="form.lastName"
              type="text"
              label="Nom"
              placeholder="Dupont"
              :icon="UserIcon"
              :error="getError('lastName')"
              required
              autocomplete="family-name"
              @blur="handleBlur('lastName')"
              @input="clearError('lastName')"
            />
          </div>

          <!-- Email -->
          <Input
            v-model="form.email"
            type="email"
            label="Adresse email"
            placeholder="jean.dupont@example.com"
            :icon="EnvelopeIcon"
            :error="getError('email')"
            required
            autocomplete="email"
            @blur="handleBlur('email')"
            @input="clearError('email')"
          />

          <!-- Password Fields -->
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Input
              v-model="form.password"
              type="password"
              label="Mot de passe"
              placeholder="••••••••"
              :icon="LockClosedIcon"
              :error="getError('password')"
              hint="Min. 8 caractères, 1 majuscule, 1 chiffre"
              required
              autocomplete="new-password"
              @blur="handleBlur('password')"
              @input="clearError('password')"
            />

            <Input
              v-model="form.password_confirmation"
              type="password"
              label="Confirmer le mot de passe"
              placeholder="••••••••"
              :icon="LockClosedIcon"
              :error="getError('password_confirmation')"
              required
              autocomplete="new-password"
              @blur="handleBlur('password_confirmation')"
              @input="clearError('password_confirmation')"
            />
          </div>

          <!-- Age -->
          <Input
            v-model="form.age"
            type="number"
            label="Âge"
            placeholder="25"
            :error="getError('age')"
            required
            min="13"
            max="120"
            @blur="handleBlur('age')"
            @input="clearError('age')"
          />

          <!-- Location Fields -->
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Select
              v-model="form.province"
              label="Province"
              placeholder="Sélectionnez une province"
              :options="provinceOptions"
              :error="getError('province')"
              required
              @blur="handleBlur('province')"
              @change="clearError('province')"
            />

            <Input
              v-model="form.commune"
              type="text"
              label="Commune"
              placeholder="Ex: Bab Ezzouar"
              :error="getError('commune')"
              required
              @blur="handleBlur('commune')"
              @input="clearError('commune')"
            />
          </div>

          <!-- Phone Number -->
          <Input
            v-model="form.phoneNumber"
            type="tel"
            label="Numéro de téléphone"
            placeholder="+213 555 123 456"
            :icon="PhoneIcon"
            :error="getError('phoneNumber')"
            hint="Optionnel - Format: +213 5XX XX XX XX"
            autocomplete="tel"
            @blur="handleBlur('phoneNumber')"
            @input="clearError('phoneNumber')"
          />

          <!-- Submit Button -->
          <Button
            type="submit"
            variant="primary"
            size="lg"
            :loading="form.processing"
            :disabled="form.processing"
            full-width
          >
            Créer mon compte
          </Button>

          <!-- Login Link -->
          <p
            class="text-center text-sm text-sand-11"
            v-motion
            :initial="{ opacity: 0 }"
            :enter="{ opacity: 1, transition: { delay: 150 } }"
          >
            Vous avez déjà un compte ?
            <Link
              href="/auth/login"
              class="text-primary-600 hover:text-primary-700 font-semibold transition-colors"
            >
              Se connecter
            </Link>
          </p>
        </form>
      </section>
    </div>
  </AuthLayout>
</template>
