// inertia/components/shared/FlashMessage.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { usePage } from '@inertiajs/vue3'
import Alert from '#ui/Alert.vue'
import type { FlashMessages } from '~/types/common'
import type { AlertType } from '~/types'

interface FlashMessage {
  type: AlertType
  message: string
}

const page = usePage()
const dismissedMessages = ref<Set<string>>(new Set())

const flash = computed<FlashMessages>(() => {
  const props = page.props as any
  return {
    success: props.flash?.success,
    error: props.flash?.error,
    warning: props.flash?.warning,
    info: props.flash?.info,
  }
})

const visibleMessages = computed<FlashMessage[]>(() => {
  const messages: FlashMessage[] = []

  if (flash.value.success && !dismissedMessages.value.has('success')) {
    messages.push({ type: 'success', message: flash.value.success })
  }
  if (flash.value.error && !dismissedMessages.value.has('error')) {
    messages.push({ type: 'error', message: flash.value.error })
  }
  if (flash.value.warning && !dismissedMessages.value.has('warning')) {
    messages.push({ type: 'warning', message: flash.value.warning })
  }
  if (flash.value.info && !dismissedMessages.value.has('info')) {
    messages.push({ type: 'info', message: flash.value.info })
  }

  return messages
})

const dismiss = (type: string) => {
  dismissedMessages.value.add(type)
}
</script>

<template>
  <div
    v-if="visibleMessages.length"
    class="fixed top-20 left-4 right-4 md:left-auto md:right-8 z-50 space-y-2 max-w-md"
  >
    <TransitionGroup name="slide-fade">
      <Alert
        v-for="msg in visibleMessages"
        :key="msg.type"
        :type="msg.type"
        dismissible
        @dismiss="dismiss(msg.type)"
      >
        {{ msg.message }}
      </Alert>
    </TransitionGroup>
  </div>
</template>

<style scoped>
.slide-fade-enter-active,
.slide-fade-leave-active {
  transition: all 0.3s ease;
}

.slide-fade-enter-from {
  transform: translateX(20px);
  opacity: 0;
}

.slide-fade-leave-to {
  transform: translateX(20px);
  opacity: 0;
}

.slide-fade-move {
  transition: transform 0.3s ease;
}
</style>

// inertia/components/shared/FlashMessage.tsx
import { useState, useEffect } from 'react'
import { usePage } from '@inertiajs/react'
import { AnimatePresence, motion } from 'motion/react'
import Alert from '~/components/ui/Alert'
import type { AlertType } from '~/types'

interface FlashMessages {
  success?: string
  error?: string
  warning?: string
  info?: string
}

interface FlashMessage {
  type: AlertType
  message: string
}

export default function FlashMessages() {
  const { props } = usePage()
  const [dismissedMessages, setDismissedMessages] = useState<Set<string>>(new Set())
  const [mounted, setMounted] = useState(false)

  const flash = props.flash as FlashMessages | undefined

  useEffect(() => {
    setMounted(true)
  }, [])

  const visibleMessages: FlashMessage[] = []

  if (mounted && flash) {
    if (flash.success && !dismissedMessages.has('success')) {
      visibleMessages.push({ type: 'success', message: flash.success })
    }
    if (flash.error && !dismissedMessages.has('error')) {
      visibleMessages.push({ type: 'error', message: flash.error })
    }
    if (flash.warning && !dismissedMessages.has('warning')) {
      visibleMessages.push({ type: 'warning', message: flash.warning })
    }
    if (flash.info && !dismissedMessages.has('info')) {
      visibleMessages.push({ type: 'info', message: flash.info })
    }
  }

  const dismiss = (type: string) => {
    setDismissedMessages((prev) => new Set([...prev, type]))
  }

  if (visibleMessages.length === 0) return null

  return (
    <div className="fixed top-20 left-4 right-4 md:left-auto md:right-8 z-50 space-y-2 max-w-md">
      <AnimatePresence>
        {visibleMessages.map((msg) => (
          <motion.div
            key={msg.type}
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 20 }}
            transition={{ duration: 0.3 }}
          >
            <Alert type={msg.type} dismissible onDismiss={() => dismiss(msg.type)}>
              {msg.message}
            </Alert>
          </motion.div>
        ))}
      </AnimatePresence>
    </div>
  )
}
