// inertia/pages/profile/show.tsx
import { Head, router } from '@inertiajs/react'
import { useState } from 'react'
import { motion } from 'motion/react'
import {
  UserCircleIcon,
  EnvelopeIcon,
  PhoneIcon,
  MapPinIcon,
  CalendarIcon,
  CameraIcon,
  TrashIcon,
  CheckCircleIcon,
} from '@heroicons/react/24/outline'
import AppLayout from '~/components/layouts/AppLayout'
import Card from '~/components/ui/Card'
import Button from '~/components/ui/Button'
import Input from '~/components/ui/Input'
import Select from '~/components/ui/Select'
import Avatar from '~/components/ui/Avatar'
import Badge from '~/components/ui/Badge'
import Alert from '~/components/ui/Alert'
import Modal from '~/components/ui/Modal'
import { useValidatedForm } from '~/hooks/useValidatedForm'
import { useRouteGuard } from '~/hooks/useRouteGuard'
import { updateProfileSchema } from '~/lib/validation'
import { useFileUpload } from '~/hooks/useFileUpload'
import { PROVINCES } from '~/lib/constants'
import { formatDate } from '~/lib/utils'

interface User {
  id: number
  firstName: string
  lastName: string
  email: string
  age: number
  province: string
  commune: string
  phoneNumber?: string
  avatarUrl?: string
  isEmailVerified: boolean
  createdAt: string
}

interface Props {
  user: User
}

export default function ProfileShow({ user }: Props) {
  useRouteGuard({ requiresAuth: true })

  const [isEditing, setIsEditing] = useState(false)
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  const [isDeletingAvatar, setIsDeletingAvatar] = useState(false)

  const { files, previews, handleFiles, clearFiles } = useFileUpload({
    maxSize: 2 * 1024 * 1024,
    allowedTypes: ['image/jpeg', 'image/png', 'image/webp'],
    multiple: false,
  })

  const { form, getError, handleBlur, shouldShowError } = useValidatedForm({
    schema: updateProfileSchema,
    initialData: {
      firstName: user.firstName,
      lastName: user.lastName,
      age: user.age,
      province: user.province,
      commune: user.commune,
      phoneNumber: user.phoneNumber || '',
    },
  })

  const provinceOptions = PROVINCES.map((p) => ({
    value: p,
    label: p,
  }))

  const handleSubmit = async () => {
    const formData = new FormData()
    formData.append('firstName', form.data.firstName)
    formData.append('lastName', form.data.lastName)
    formData.append('age', String(form.data.age))
    formData.append('province', form.data.province)
    formData.append('commune', form.data.commune)
    if (form.data.phoneNumber) {
      formData.append('phoneNumber', form.data.phoneNumber)
    }
    if (files[0]) {
      formData.append('avatar', files[0])
    }

    router.post('/profile', formData as any, {
      preserveScroll: true,
      onSuccess: () => {
        setIsEditing(false)
        clearFiles()
      },
    })
  }

  const handleDeleteAvatar = () => {
    setIsDeletingAvatar(true)
    router.delete('/profile/avatar', {
      preserveScroll: true,
      onSuccess: () => {
        setShowDeleteModal(false)
        setIsDeletingAvatar(false)
      },
      onError: () => {
        setIsDeletingAvatar(false)
      },
    })
  }

  const handleCancel = () => {
    form.reset()
    clearFiles()
    setIsEditing(false)
  }

  return (
    <>
      <Head title="Mon Profil" />
      <AppLayout>
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {/* Header */}
          <motion.div
            className="mb-8"
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4 }}
          >
            <h1 className="text-3xl font-bold text-neutral-900 mb-2">Mon Profil</h1>
            <p className="text-neutral-600">
              Gérez vos informations personnelles et vos préférences
            </p>
          </motion.div>

          {/* Email Verification Alert */}
          {!user.isEmailVerified && (
            <motion.div
              className="mb-6"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.4, delay: 0.1 }}
            >
              <Alert type="warning">
                Votre email n'est pas encore vérifié. Veuillez vérifier votre boîte de réception.
              </Alert>
            </motion.div>
          )}

          <div className="grid lg:grid-cols-3 gap-8">
            {/* Profile Card */}
            <motion.div
              className="lg:col-span-1"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.4, delay: 0.2 }}
            >
              <Card className="text-center">
                <div className="relative inline-block mb-6">
                  <Avatar
                    name={`${user.firstName} ${user.lastName}`}
                    src={user.avatarUrl}
                    size="2xl"
                    ring
                  />
                  {user.isEmailVerified && (
                    <div className="absolute -bottom-1 -right-1 w-8 h-8 bg-success-500 rounded-full border-4 border-white flex items-center justify-center">
                      <CheckCircleIcon className="w-5 h-5 text-white" />
                    </div>
                  )}
                </div>

                <h2 className="text-2xl font-bold text-neutral-900 mb-1">
                  {user.firstName} {user.lastName}
                </h2>
                <p className="text-neutral-600 mb-4">{user.email}</p>

                <div className="space-y-2 mb-6">
                  <Badge variant="primary" size="lg">
                    {user.age} ans
                  </Badge>
                  <p className="text-sm text-neutral-600">
                    Membre depuis {formatDate(user.createdAt)}
                  </p>
                </div>

                {!isEditing && (
                  <div className="space-y-2">
                    <Button variant="primary" fullWidth onClick={() => setIsEditing(true)}>
                      Modifier le profil
                    </Button>
                    {user.avatarUrl && (
                      <Button
                        variant="outline"
                        fullWidth
                        iconLeft={TrashIcon}
                        onClick={() => setShowDeleteModal(true)}
                      >
                        Supprimer la photo
                      </Button>
                    )}
                  </div>
                )}
              </Card>
            </motion.div>

            {/* Information Card */}
            <motion.div
              className="lg:col-span-2"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.4, delay: 0.3 }}
            >
              <Card>
                <div className="flex items-center justify-between mb-6">
                  <h3 className="text-xl font-bold text-neutral-900">Informations personnelles</h3>
                  {isEditing && (
                    <Badge variant="info" pulse>
                      Mode édition
                    </Badge>
                  )}
                </div>

                {!isEditing ? (
                  <div className="space-y-6">
                    <div className="grid sm:grid-cols-2 gap-6">
                      <div className="flex items-start gap-3">
                        <UserCircleIcon className="w-6 h-6 text-primary-600 mt-1" />
                        <div>
                          <p className="text-sm font-semibold text-neutral-700">Prénom</p>
                          <p className="text-neutral-900">{user.firstName}</p>
                        </div>
                      </div>

                      <div className="flex items-start gap-3">
                        <UserCircleIcon className="w-6 h-6 text-primary-600 mt-1" />
                        <div>
                          <p className="text-sm font-semibold text-neutral-700">Nom</p>
                          <p className="text-neutral-900">{user.lastName}</p>
                        </div>
                      </div>

                      <div className="flex items-start gap-3">
                        <EnvelopeIcon className="w-6 h-6 text-primary-600 mt-1" />
                        <div>
                          <p className="text-sm font-semibold text-neutral-700">Email</p>
                          <p className="text-neutral-900">{user.email}</p>
                        </div>
                      </div>

                      <div className="flex items-start gap-3">
                        <CalendarIcon className="w-6 h-6 text-primary-600 mt-1" />
                        <div>
                          <p className="text-sm font-semibold text-neutral-700">Âge</p>
                          <p className="text-neutral-900">{user.age} ans</p>
                        </div>
                      </div>

                      <div className="flex items-start gap-3">
                        <MapPinIcon className="w-6 h-6 text-primary-600 mt-1" />
                        <div>
                          <p className="text-sm font-semibold text-neutral-700">Wilaya</p>
                          <p className="text-neutral-900">{user.province}</p>
                        </div>
                      </div>

                      <div className="flex items-start gap-3">
                        <MapPinIcon className="w-6 h-6 text-primary-600 mt-1" />
                        <div>
                          <p className="text-sm font-semibold text-neutral-700">Commune</p>
                          <p className="text-neutral-900">{user.commune}</p>
                        </div>
                      </div>

                      {user.phoneNumber && (
                        <div className="flex items-start gap-3">
                          <PhoneIcon className="w-6 h-6 text-primary-600 mt-1" />
                          <div>
                            <p className="text-sm font-semibold text-neutral-700">Téléphone</p>
                            <p className="text-neutral-900">{user.phoneNumber}</p>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                ) : (
                  <div className="space-y-6">
                    {/* Avatar Upload */}
                    <div>
                      <label className="block text-sm font-semibold text-neutral-800 mb-3">
                        Photo de profil
                      </label>
                      <div className="flex items-center gap-4">
                        <Avatar
                          name={`${form.data.firstName} ${form.data.lastName}`}
                          src={previews[0] || user.avatarUrl}
                          size="xl"
                        />
                        <div className="flex-1">
                          <input
                            type="file"
                            id="avatar"
                            accept="image/*"
                            onChange={handleFiles}
                            className="hidden"
                          />
                          <label htmlFor="avatar">
                            <Button
                              variant="outline"
                              size="sm"
                              iconLeft={CameraIcon}
                              className="cursor-pointer"
                            >
                              Changer la photo
                            </Button>
                          </label>
                          <p className="text-xs text-neutral-500 mt-2">
                            JPG, PNG ou WEBP. Max 2MB.
                          </p>
                        </div>
                      </div>
                    </div>

                    <div className="grid sm:grid-cols-2 gap-4">
                      <Input
                        label="Prénom"
                        value={form.data.firstName}
                        onChange={(value) => form.setData('firstName', value as string)}
                        onBlur={() => handleBlur('firstName')}
                        error={shouldShowError('firstName') ? getError('firstName') : undefined}
                        icon={UserCircleIcon}
                        required
                        disabled={form.processing}
                      />

                      <Input
                        label="Nom"
                        value={form.data.lastName}
                        onChange={(value) => form.setData('lastName', value as string)}
                        onBlur={() => handleBlur('lastName')}
                        error={shouldShowError('lastName') ? getError('lastName') : undefined}
                        icon={UserCircleIcon}
                        required
                        disabled={form.processing}
                      />

                      <Input
                        label="Âge"
                        type="number"
                        value={form.data.age}
                        onChange={(value) => form.setData('age', value as number)}
                        onBlur={() => handleBlur('age')}
                        error={shouldShowError('age') ? getError('age') : undefined}
                        icon={CalendarIcon}
                        required
                        min={13}
                        max={120}
                        disabled={form.processing}
                      />

                      <Input
                        label="Téléphone"
                        type="tel"
                        value={form.data.phoneNumber}
                        onChange={(value) => form.setData('phoneNumber', value as string)}
                        onBlur={() => handleBlur('phoneNumber')}
                        error={shouldShowError('phoneNumber') ? getError('phoneNumber') : undefined}
                        icon={PhoneIcon}
                        placeholder="+213 555 123 456"
                        disabled={form.processing}
                      />

                      <Select
                        label="Wilaya"
                        value={form.data.province}
                        onChange={(value) => form.setData('province', value as string)}
                        options={provinceOptions}
                        error={shouldShowError('province') ? getError('province') : undefined}
                        required
                        searchable
                        disabled={form.processing}
                      />

                      <Input
                        label="Commune"
                        value={form.data.commune}
                        onChange={(value) => form.setData('commune', value as string)}
                        onBlur={() => handleBlur('commune')}
                        error={shouldShowError('commune') ? getError('commune') : undefined}
                        icon={MapPinIcon}
                        required
                        disabled={form.processing}
                      />
                    </div>

                    <div className="flex gap-3 pt-4 border-t border-neutral-200">
                      <Button
                        variant="primary"
                        fullWidth
                        loading={form.processing}
                        disabled={form.processing}
                        onClick={handleSubmit}
                      >
                        Enregistrer les modifications
                      </Button>
                      <Button
                        variant="outline"
                        fullWidth
                        onClick={handleCancel}
                        disabled={form.processing}
                      >
                        Annuler
                      </Button>
                    </div>
                  </div>
                )}
              </Card>
            </motion.div>
          </div>
        </div>

        {/* Delete Avatar Modal */}
        <Modal
          show={showDeleteModal}
          onClose={() => setShowDeleteModal(false)}
          title="Supprimer la photo de profil"
          maxWidth="sm"
          footer={
            <div className="flex gap-3">
              <Button
                variant="outline"
                fullWidth
                onClick={() => setShowDeleteModal(false)}
                disabled={isDeletingAvatar}
              >
                Annuler
              </Button>
              <Button
                variant="danger"
                fullWidth
                loading={isDeletingAvatar}
                disabled={isDeletingAvatar}
                onClick={handleDeleteAvatar}
              >
                Supprimer
              </Button>
            </div>
          }
        >
          <p className="text-neutral-700">
            Êtes-vous sûr de vouloir supprimer votre photo de profil ? Cette action est
            irréversible.
          </p>
        </Modal>
      </AppLayout>
    </>
  )
}

// inertia/pages/profile/show.vue
<script setup lang="ts">
import { Head, useForm } from '@inertiajs/vue3'
import { ref } from 'vue'
import { UserIcon, EnvelopeIcon, PhoneIcon, MapPinIcon, CakeIcon, TrashIcon } from '@heroicons/vue/24/outline'
import AppLayout from '~/components/layouts/AppLayout'
import Input from '#ui/Input.vue'
import Select from '#ui/Select.vue'
import Button from '#ui/Button.vue'
import Card from '#ui/Card.vue'
import Avatar from '#ui/Avatar.vue'
import { useProtectedLayout } from '#composables/use_protected_layout'
import { PROVINCES } from '#lib/constants'

interface User {
  id: number
  firstName: string
  lastName: string
  email: string
  age: number
  province: string
  commune: string
  phoneNumber: string | null
  avatarUrl: string | null
  isEmailVerified: boolean
  createdAt: string
}

interface PageProps {
  user: User
}

const props = defineProps<PageProps>()

// Protect page - require authentication
useProtectedLayout({ requiresAuth: true })

const form = useForm({
  firstName: props.user.firstName,
  lastName: props.user.lastName,
  age: props.user.age,
  province: props.user.province,
  commune: props.user.commune,
  phoneNumber: props.user.phoneNumber || '',
  avatar: null as File | null,
})

const provinces = PROVINCES.map((p) => ({ value: p, label: p }))
const previewUrl = ref<string | null>(null)
const showDeleteConfirm = ref(false)

const handleFileChange = (event: Event) => {
  const target = event.target as HTMLInputElement
  const file = target.files?.[0]

  if (file) {
    form.avatar = file
    previewUrl.value = URL.createObjectURL(file)
  }
}

const submit = () => {
  form.post('/profile', {
    preserveScroll: true,
    onSuccess: () => {
      previewUrl.value = null
    },
  })
}

const deleteAvatar = () => {
  showDeleteConfirm.value = true
}

const confirmDeleteAvatar = () => {
  form.delete('/profile/avatar', {
    preserveScroll: true,
    onSuccess: () => {
      showDeleteConfirm.value = false
    },
  })
}
</script>

<template>
  <Head title="My Profile" />

  <AppLayout>
    <!-- Header -->
    <div
      class="mb-8"
      v-motion
      :initial="{ opacity: 0, y: -20 }"
      :enter="{ opacity: 1, y: 0, transition: { duration: 400 } }"
    >
      <h1 class="text-4xl font-bold text-neutral-900 mb-2">My Profile</h1>
      <p class="text-neutral-600">Manage your personal information and preferences</p>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
      <!-- Sidebar -->
      <div class="lg:col-span-1">
        <Card
          class="sticky top-20"
          v-motion
          :initial="{ opacity: 0, x: -20 }"
          :enter="{ opacity: 1, x: 0, transition: { duration: 400, delay: 100 } }"
        >
          <!-- Avatar Section -->
          <div class="text-center pb-6 border-b border-neutral-200">
            <div class="relative inline-block mb-4">
              <Avatar
                :src="previewUrl || user.avatarUrl as string | undefined"
                :name="`${user.firstName} ${user.lastName}`"
                size="xl"
              />
              <label
                for="avatar-input"
                class="absolute bottom-0 right-0 bg-primary-600 hover:bg-primary-700 text-white p-2 rounded-full cursor-pointer transition shadow-lg"
              >
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z"
                  />
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M15 13a3 3 0 11-6 0 3 3 0 016 0z"
                  />
                </svg>
              </label>
              <input
                id="avatar-input"
                type="file"
                accept="image/jpeg,image/jpg,image/png,image/webp"
                @change="handleFileChange"
                class="hidden"
              />
            </div>

            <h2 class="text-2xl font-bold text-neutral-900">
              {{ user.firstName }} {{ user.lastName }}
            </h2>
            <p class="text-neutral-600 mt-1">{{ user.email }}</p>

            <!-- Email Verification Status -->
            <div class="mt-4 pt-4 border-t border-neutral-200">
              <div class="flex items-center justify-center gap-2">
                <div
                  :class="[
                    'w-3 h-3 rounded-full',
                    user.isEmailVerified ? 'bg-success-500' : 'bg-warning-500',
                  ]"
                />
                <span class="text-sm font-medium text-neutral-700">
                  {{ user.isEmailVerified ? 'Email Verified' : 'Email Pending Verification' }}
                </span>
              </div>
            </div>

            <!-- Member Since -->
            <p class="text-xs text-neutral-500 mt-3">
              Member since {{ new Date(user.createdAt).toLocaleDateString() }}
            </p>
          </div>

          <!-- Delete Avatar Button -->
          <div v-if="user.avatarUrl && !previewUrl" class="pt-4">
            <Button
              variant="danger"
              size="sm"
              full-width
              :icon-left="TrashIcon"
              @click="deleteAvatar"
            >
              Delete Photo
            </Button>
          </div>
        </Card>
      </div>

      <!-- Main Form -->
      <div class="lg:col-span-2">
        <Card
          v-motion
          :initial="{ opacity: 0, x: 20 }"
          :enter="{ opacity: 1, x: 0, transition: { duration: 400, delay: 150 } }"
        >
          <form @submit.prevent="submit" class="space-y-6">
            <!-- Avatar Upload Preview -->
            <div v-if="previewUrl" class="p-4 bg-primary-50 border border-primary-200 rounded-lg">
              <p class="text-sm font-medium text-primary-900 mb-2">
                New photo ready to upload
              </p>
              <div class="flex items-center justify-between">
                <img :src="previewUrl" alt="Preview" class="h-16 w-16 object-cover rounded" />
                <Button variant="primary" size="sm" type="submit" :loading="form.processing">
                  Save Photo
                </Button>
              </div>
            </div>

            <!-- Personal Information Section -->
            <div>
              <h3 class="text-lg font-semibold text-neutral-900 mb-4">Personal Information</h3>
              <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Input
                  v-model="form.firstName"
                  type="text"
                  label="First Name"
                  :icon="UserIcon"
                  required
                  :error="form.errors.firstName"
                />
                <Input
                  v-model="form.lastName"
                  type="text"
                  label="Last Name"
                  :icon="UserIcon"
                  required
                  :error="form.errors.lastName"
                />
              </div>
            </div>

            <!-- Contact Information Section -->
            <div>
              <h3 class="text-lg font-semibold text-neutral-900 mb-4">Contact Information</h3>
              <div class="space-y-4">
                <Input
                  :value="user.email"
                  type="email"
                  label="Email Address"
                  :icon="EnvelopeIcon"
                  disabled
                  hint="Email cannot be changed"
                />
                <Input
                  v-model="form.phoneNumber"
                  type="tel"
                  label="Phone Number (Optional)"
                  :icon="PhoneIcon"
                  placeholder="+213 5XX XX XX XX"
                  :error="form.errors.phoneNumber"
                />
              </div>
            </div>

            <!-- Location & Age Section -->
            <div>
              <h3 class="text-lg font-semibold text-neutral-900 mb-4">Location & Age</h3>
              <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                <Input
                  v-model.number="form.age"
                  type="number"
                  label="Age"
                  :icon="CakeIcon"
                  min="13"
                  max="120"
                  required
                  :error="form.errors.age"
                />
                <Select
                  v-model="form.province"
                  label="Province"
                  :options="provinces"
                  required
                  :error="form.errors.province"
                  searchable
                />
                <Input
                  v-model="form.commune"
                  type="text"
                  label="Commune"
                  :icon="MapPinIcon"
                  required
                  :error="form.errors.commune"
                />
              </div>
            </div>

            <!-- Actions -->
            <div class="flex gap-3 pt-4 border-t border-neutral-200">
              <Button
                type="submit"
                variant="primary"
                size="lg"
                :loading="form.processing"
                :disabled="form.processing"
                class="flex-1"
              >
                Save Changes
              </Button>
            </div>
          </form>
        </Card>
      </div>
    </div>

    <!-- Delete Confirmation Modal -->
    <div
      v-if="showDeleteConfirm"
      class="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"
    >
      <Card class="max-w-md w-full">
        <h3 class="text-xl font-bold text-neutral-900 mb-2">Delete Photo?</h3>
        <p class="text-neutral-600 mb-6">
          Are you sure you want to delete your profile photo? This action cannot be undone.
        </p>
        <div class="flex gap-3">
          <Button
            variant="ghost"
            class="flex-1"
            @click="showDeleteConfirm = false"
          >
            Cancel
          </Button>
          <Button
            variant="danger"
            class="flex-1"
            :loading="form.processing"
            @click="confirmDeleteAvatar"
          >
            Delete
          </Button>
        </div>
      </Card>
    </div>
  </AppLayout>
</template>
