// inertia/pages/registrations/index.vue
<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3'
import { ref, computed } from 'vue'
import { TrashIcon, EyeIcon, CalendarIcon, MapPinIcon } from '@heroicons/vue/24/outline'
import AppLayout from '~/components/layouts/AppLayout'
import Button from '#ui/Button.vue'
import Card from '#ui/Card.vue'
import Badge from '#ui/Badge.vue'
import Image from '#ui/Image.vue'
import { useProtectedLayout } from '#composables/use_protected_layout'

interface Registration {
  id: number
  status: 'pending' | 'confirmed' | 'attended' | 'canceled'
  qrCode: string
  registeredAt: string
  hasAttended: boolean
  event: {
    id: number
    name: string
    location: string
    startDate: string
    endDate: string
    imageUrl: string | null
    isUpcoming: boolean
    isOngoing: boolean
    isPast: boolean
  }
}

interface PageProps {
  registrations: Registration[]
}

const props = defineProps<PageProps>()

// Protect page - require authentication
useProtectedLayout({ requiresAuth: true })

const cancelingId = ref<number | null>(null)

const statusConfig = {
  pending: { label: 'Pending', color: 'warning' as const },
  confirmed: { label: 'Confirmed', color: 'success' as const },
  attended: { label: 'Attended', color: 'info' as const },
  canceled: { label: 'Canceled', color: 'error' as const },
}

const eventStatusConfig = {
  upcoming: { label: 'Upcoming', color: 'info' as const },
  ongoing: { label: 'Ongoing', color: 'warning' as const },
  finished: { label: 'Finished', color: 'neutral' as const },
}

const groupedRegistrations = computed(() => {
  const groups: Record<string, Registration[]> = {
    upcoming: [],
    past: [],
    attended: [],
  }

  props.registrations.forEach((reg) => {
    if (reg.hasAttended) {
      groups.attended.push(reg)
    } else if (reg.event.isUpcoming) {
      groups.upcoming.push(reg)
    } else {
      groups.past.push(reg)
    }
  })

  return groups
})

const cancelRegistration = (id: number) => {
  if (confirm('Are you sure you want to cancel this registration? This action cannot be undone.')) {
    cancelingId.value = id
    router.delete(`/registrations/${id}`, {
      preserveScroll: true,
      onFinish: () => {
        cancelingId.value = null
      },
    })
  }
}

const getEventStatus = (event: Registration['event']) => {
  if (event.isUpcoming) return eventStatusConfig.upcoming
  if (event.isOngoing) return eventStatusConfig.ongoing
  return eventStatusConfig.finished
}
</script>

<template>
  <Head title="My Registrations" />

  <AppLayout>
    <!-- Header -->
    <div class="mb-8">
      <h1
        class="text-4xl font-bold text-neutral-900 mb-2"
        v-motion
        :initial="{ opacity: 0, y: -20 }"
        :enter="{ opacity: 1, y: 0, transition: { duration: 400 } }"
      >
        My Event Registrations
      </h1>
      <p
        class="text-neutral-600"
        v-motion
        :initial="{ opacity: 0, y: -10 }"
        :enter="{ opacity: 1, y: 0, transition: { duration: 400, delay: 100 } }"
      >
        Manage your event registrations and view your QR codes
      </p>
    </div>

    <!-- Stats -->
    <div
      class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8"
      v-motion
      :initial="{ opacity: 0, y: 20 }"
      :enter="{ opacity: 1, y: 0, transition: { duration: 400, delay: 150 } }"
    >
      <Card class="text-center">
        <div class="text-3xl font-bold text-primary-600">{{ props.registrations.length }}</div>
        <div class="text-sm text-neutral-600 mt-1">Total Registrations</div>
      </Card>
      <Card class="text-center">
        <div class="text-3xl font-bold text-info-600">
          {{ groupedRegistrations.upcoming.length }}
        </div>
        <div class="text-sm text-neutral-600 mt-1">Upcoming Events</div>
      </Card>
      <Card class="text-center">
        <div class="text-3xl font-bold text-success-600">
          {{ groupedRegistrations.attended.length }}
        </div>
        <div class="text-sm text-neutral-600 mt-1">Events Attended</div>
      </Card>
    </div>

    <!-- Upcoming Registrations -->
    <section v-if="groupedRegistrations.upcoming.length > 0" class="mb-12">
      <h2 class="text-2xl font-bold text-neutral-900 mb-6">Upcoming Events</h2>
      <div class="space-y-4">
        <div
          v-for="(reg, index) in groupedRegistrations.upcoming"
          :key="reg.id"
          v-motion
          :initial="{ opacity: 0, x: -20 }"
          :enter="{
            opacity: 1,
            x: 0,
            transition: { duration: 300, delay: index * 50 },
          }"
        >
          <Card class="overflow-hidden hover:shadow-lg transition-shadow">
            <div class="grid grid-cols-1 md:grid-cols-4 gap-6 p-6">
              <!-- Image -->
              <div class="relative h-40 md:h-full rounded-lg overflow-hidden bg-neutral-200">
                <Image
                  :src="reg.event.imageUrl as string | undefined"
                  :alt="reg.event.name"
                  aspect-ratio="16/9"
                  class="group-hover:scale-105 transition-transform duration-300"
                />
              </div>

              <!-- Content -->
              <div class="md:col-span-2 space-y-3">
                <div class="flex items-start justify-between gap-2">
                  <div>
                    <h3 class="text-lg font-bold text-neutral-900">{{ reg.event.name }}</h3>
                    <Badge
                      :variant="statusConfig[reg.status].color"
                      size="sm"
                      class="mt-2"
                    >
                      {{ statusConfig[reg.status].label }}
                    </Badge>
                  </div>
                  <Badge
                    :variant="getEventStatus(reg.event).color"
                    size="sm"
                  >
                    {{ getEventStatus(reg.event).label }}
                  </Badge>
                </div>

                <div class="space-y-2 text-sm">
                  <div class="flex items-center gap-2 text-neutral-600">
                    <CalendarIcon class="w-4 h-4 flex-shrink-0 text-primary-500" />
                    <span>{{ reg.event.startDate }}</span>
                  </div>
                  <div class="flex items-center gap-2 text-neutral-600">
                    <MapPinIcon class="w-4 h-4 flex-shrink-0 text-primary-500" />
                    <span>{{ reg.event.location }}</span>
                  </div>
                </div>

                <p class="text-xs text-neutral-500">
                  Registered on {{ reg.registeredAt }}
                </p>
              </div>

              <!-- Actions -->
              <div class="flex flex-col gap-2">
                <Link
                  :href="`/registrations/${reg.id}`"
                  class="flex-1"
                >
                  <Button variant="primary" size="md" full-width :icon-left="EyeIcon">
                    View QR Code
                  </Button>
                </Link>

                <Button
                  v-if="reg.event.isUpcoming && reg.status !== 'canceled'"
                  variant="danger"
                  size="md"
                  full-width
                  :icon-left="TrashIcon"
                  :loading="cancelingId === reg.id"
                  :disabled="cancelingId === reg.id"
                  @click="cancelRegistration(reg.id)"
                >
                  Cancel
                </Button>

                <Link :href="`/events/${reg.event.id}`" class="flex-1">
                  <Button variant="ghost" size="md" full-width>
                    Event Details
                  </Button>
                </Link>
              </div>
            </div>
          </Card>
        </div>
      </div>
    </section>

    <!-- Past Registrations -->
    <section v-if="groupedRegistrations.past.length > 0" class="mb-12">
      <h2 class="text-2xl font-bold text-neutral-900 mb-6">Past Events</h2>
      <div class="space-y-4">
        <div
          v-for="(reg, index) in groupedRegistrations.past"
          :key="reg.id"
          v-motion
          :initial="{ opacity: 0, x: -20 }"
          :enter="{
            opacity: 1,
            x: 0,
            transition: { duration: 300, delay: index * 50 },
          }"
        >
          <Card class="overflow-hidden opacity-75 hover:opacity-100 transition-opacity">
            <div class="grid grid-cols-1 md:grid-cols-4 gap-6 p-6">
              <!-- Image -->
              <div class="relative h-40 md:h-full rounded-lg overflow-hidden bg-neutral-200">
                <Image
                  :src="reg.event.imageUrl as string | undefined"
                  :alt="reg.event.name"
                  aspect-ratio="16/9"
                />
              </div>

              <!-- Content -->
              <div class="md:col-span-3 space-y-3">
                <div class="flex items-start justify-between gap-2">
                  <div>
                    <h3 class="text-lg font-bold text-neutral-900">{{ reg.event.name }}</h3>
                    <Badge
                      :variant="statusConfig[reg.status].color"
                      size="sm"
                      class="mt-2"
                    >
                      {{ statusConfig[reg.status].label }}
                    </Badge>
                  </div>
                  <Badge variant="neutral" size="sm">
                    Finished
                  </Badge>
                </div>

                <div class="space-y-2 text-sm">
                  <div class="flex items-center gap-2 text-neutral-600">
                    <CalendarIcon class="w-4 h-4 flex-shrink-0" />
                    <span>{{ reg.event.endDate }}</span>
                  </div>
                  <div class="flex items-center gap-2 text-neutral-600">
                    <MapPinIcon class="w-4 h-4 flex-shrink-0" />
                    <span>{{ reg.event.location }}</span>
                  </div>
                </div>

                <div v-if="reg.hasAttended" class="inline-flex items-center gap-1 text-success-600 text-sm font-medium">
                  <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                    <path
                      fill-rule="evenodd"
                      d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                      clip-rule="evenodd"
                    />
                  </svg>
                  Attendance Confirmed
                </div>
              </div>
            </div>
          </Card>
        </div>
      </div>
    </section>

    <!-- Empty State -->
    <div v-if="props.registrations.length === 0" class="text-center py-16">
      <div class="text-6xl mb-4">📋</div>
      <h3 class="text-2xl font-bold text-neutral-900 mb-2">No Registrations Yet</h3>
      <p class="text-neutral-600 mb-6">
        You haven't registered for any events. Start exploring and register for upcoming events!
      </p>
      <Link href="/events">
        <Button variant="primary" size="lg">
          Discover Events
        </Button>
      </Link>
    </div>
  </AppLayout>
</template>

// inertia/pages/registrations/index.tsx
import { Head } from '@inertiajs/react'
import { useMemo } from 'react'
import { motion } from 'motion/react'
import {
  CalendarIcon,
  MapPinIcon,
  ClockIcon,
  QrCodeIcon,
  ArrowRightIcon,
  CheckCircleIcon,
  XCircleIcon,
  ClockIcon as PendingIcon,
} from '@heroicons/react/24/outline'
import AppLayout from '~/components/layouts/AppLayout'
import Card from '~/components/ui/Card'
import Button from '~/components/ui/Button'
import Badge from '~/components/ui/Badge'
import Image from '~/components/ui/Image'
import { useRouteGuard } from '~/hooks/useRouteGuard'
import { useTheme } from '~/hooks/useTheme'
import { formatDate, formatDateTime } from '~/lib/utils'

interface Event {
  id: number
  name: string
  location: string
  startDate: string
  endDate: string
  imageUrl: string | null
  status: string
}

interface Registration {
  id: number
  status: 'pending' | 'confirmed' | 'attended' | 'canceled'
  qrCode: string
  attendedAt: string | null
  createdAt: string
  event: Event
}

interface Props {
  registrations: Registration[]
}

export default function RegistrationsIndex({ registrations }: Props) {
  useRouteGuard({ requiresAuth: true, requiresVerification: true })

  const { getPlaceholder } = useTheme()

  const groupedRegistrations = useMemo(() => {
    return {
      active: registrations.filter((r) => r.status === 'confirmed' || r.status === 'pending'),
      past: registrations.filter((r) => r.status === 'attended'),
      canceled: registrations.filter((r) => r.status === 'canceled'),
    }
  }, [registrations])

  const getStatusBadge = (status: string) => {
    const badges = {
      pending: { variant: 'warning' as const, icon: PendingIcon, text: 'En attente' },
      confirmed: { variant: 'success' as const, icon: CheckCircleIcon, text: 'Confirmé' },
      attended: { variant: 'info' as const, icon: CheckCircleIcon, text: 'Présent' },
      canceled: { variant: 'neutral' as const, icon: XCircleIcon, text: 'Annulé' },
    }
    return badges[status as keyof typeof badges] || badges.pending
  }

  const renderRegistrationCard = (registration: Registration, index: number) => {
    const statusBadge = getStatusBadge(registration.status)
    const StatusIcon = statusBadge.icon

    return (
      <motion.div
        key={registration.id}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4, delay: index * 0.05 }}
      >
        <Card hoverable className="group">
          <div className="flex flex-col sm:flex-row gap-4">
            {/* Event Image */}
            <div className="sm:w-48 shrink-0">
              <Image
                src={registration.event.imageUrl || getPlaceholder('event')}
                alt={registration.event.name}
                aspectRatio="16/9"
                rounded="lg"
              />
            </div>

            {/* Content */}
            <div className="flex-1 min-w-0">
              <div className="flex items-start justify-between gap-3 mb-3">
                <div className="flex-1 min-w-0">
                  <h3 className="text-lg font-bold text-neutral-900 line-clamp-1 mb-2 group-hover:text-primary-600 transition-colors">
                    {registration.event.name}
                  </h3>
                  <div className="flex flex-wrap items-center gap-3 text-sm text-neutral-600">
                    <div className="flex items-center gap-1.5">
                      <CalendarIcon className="w-4 h-4" />
                      <span>{formatDate(registration.event.startDate)}</span>
                    </div>
                    <div className="flex items-center gap-1.5">
                      <MapPinIcon className="w-4 h-4" />
                      <span>{registration.event.location}</span>
                    </div>
                  </div>
                </div>

                <Badge variant={statusBadge.variant} size="lg" dot>
                  <StatusIcon className="w-4 h-4 mr-1.5" />
                  {statusBadge.text}
                </Badge>
              </div>

              <div className="flex items-center gap-2 text-sm text-neutral-500 mb-4">
                <ClockIcon className="w-4 h-4" />
                <span>Inscrit le {formatDateTime(registration.createdAt)}</span>
              </div>

              {/* Actions */}
              <div className="flex flex-wrap gap-2">
                <Button
                  variant="primary"
                  size="sm"
                  href={`/registrations/${registration.id}`}
                  iconRight={ArrowRightIcon}
                >
                  Voir les détails
                </Button>

                {(registration.status === 'confirmed' || registration.status === 'pending') && (
                  <Button
                    variant="outline"
                    size="sm"
                    href={`/registrations/${registration.id}`}
                    iconLeft={QrCodeIcon}
                  >
                    QR Code
                  </Button>
                )}
              </div>
            </div>
          </div>
        </Card>
      </motion.div>
    )
  }

  if (registrations.length === 0) {
    return (
      <>
        <Head title="Mes Inscriptions" />
        <AppLayout>
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            <motion.div
              className="text-center py-16"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.4 }}
            >
              <div className="text-6xl mb-4">📋</div>
              <h2 className="text-2xl font-bold text-neutral-900 mb-2">
                Aucune inscription pour le moment
              </h2>
              <p className="text-neutral-600 mb-6 max-w-md mx-auto">
                Commencez à explorer nos événements et inscrivez-vous à ceux qui vous intéressent
              </p>
              <Button variant="primary" size="lg" href="/events" iconRight={ArrowRightIcon}>
                Découvrir les événements
              </Button>
            </motion.div>
          </div>
        </AppLayout>
      </>
    )
  }

  return (
    <>
      <Head title="Mes Inscriptions" />
      <AppLayout>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {/* Header */}
          <motion.div
            className="mb-8"
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4 }}
          >
            <h1 className="text-3xl font-bold text-neutral-900 mb-2">Mes Inscriptions</h1>
            <p className="text-neutral-600">
              Gérez vos inscriptions et accédez à vos QR codes d'événements
            </p>
          </motion.div>

          {/* Stats */}
          <motion.div
            className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: 0.1 }}
          >
            <Card className="text-center">
              <div className="text-3xl font-bold text-primary-600 mb-1">
                {groupedRegistrations.active.length}
              </div>
              <p className="text-sm text-neutral-600">Inscriptions actives</p>
            </Card>
            <Card className="text-center">
              <div className="text-3xl font-bold text-info-600 mb-1">
                {groupedRegistrations.past.length}
              </div>
              <p className="text-sm text-neutral-600">Événements assistés</p>
            </Card>
            <Card className="text-center">
              <div className="text-3xl font-bold text-neutral-600 mb-1">{registrations.length}</div>
              <p className="text-sm text-neutral-600">Total d'inscriptions</p>
            </Card>
          </motion.div>

          {/* Active Registrations */}
          {groupedRegistrations.active.length > 0 && (
            <motion.div
              className="mb-12"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.4, delay: 0.2 }}
            >
              <h2 className="text-2xl font-bold text-neutral-900 mb-6 flex items-center gap-2">
                <div className="w-2 h-8 bg-primary-600 rounded-full" />
                Inscriptions actives
              </h2>
              <div className="space-y-4">
                {groupedRegistrations.active.map((reg, index) =>
                  renderRegistrationCard(reg, index)
                )}
              </div>
            </motion.div>
          )}

          {/* Past Events */}
          {groupedRegistrations.past.length > 0 && (
            <motion.div
              className="mb-12"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.4, delay: 0.3 }}
            >
              <h2 className="text-2xl font-bold text-neutral-900 mb-6 flex items-center gap-2">
                <div className="w-2 h-8 bg-info-600 rounded-full" />
                Événements passés
              </h2>
              <div className="space-y-4">
                {groupedRegistrations.past.map((reg, index) => renderRegistrationCard(reg, index))}
              </div>
            </motion.div>
          )}

          {/* Canceled */}
          {groupedRegistrations.canceled.length > 0 && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.4, delay: 0.4 }}
            >
              <h2 className="text-2xl font-bold text-neutral-900 mb-6 flex items-center gap-2">
                <div className="w-2 h-8 bg-neutral-400 rounded-full" />
                Inscriptions annulées
              </h2>
              <div className="space-y-4">
                {groupedRegistrations.canceled.map((reg, index) =>
                  renderRegistrationCard(reg, index)
                )}
              </div>
            </motion.div>
          )}
        </div>
      </AppLayout>
    </>
  )
}
