// inertia/pages/events/index.vue
<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3'
import { ref, computed } from 'vue'
import { MagnifyingGlassIcon, AdjustmentsHorizontalIcon, XMarkIcon, CalendarIcon, MapPinIcon, UsersIcon } from '@heroicons/vue/24/outline'
import AppLayout from '~/components/layouts/AppLayout'
import Input from '#ui/Input.vue'
import Select from '#ui/Select.vue'
import Button from '#ui/Button.vue'
import Card from '#ui/Card.vue'
import Badge from '#ui/Badge.vue'
import Image from '#ui/Image.vue'
import { PROVINCES, EVENT_CATEGORIES } from '#lib/constants'

interface Event {
  id: number
  name: string
  description: string
  location: string
  province: string
  startDate: string
  basePrice: number
  imageUrl: string | null
  category: string
  registeredCount: number
  capacity: number
  isFull: boolean
  canRegister: boolean
}

interface PageProps {
  events: {
    data: Event[]
    meta: {
      total: number
      per_page: number
      current_page: number
      last_page: number
    }
  }
  filters: {
    category?: string
    search?: string
    province?: string
  }
}

const props = defineProps<PageProps>()

const searchQuery = ref(props.filters.search || '')
const selectedCategory = ref(props.filters.category || '')
const selectedProvince = ref(props.filters.province || '')
const showFilters = ref(false)

const provinceOptions = PROVINCES.map((p) => ({ value: p, label: p }))
const categoryOptions = EVENT_CATEGORIES.map((c) => ({ value: c, label: c }))

const hasActiveFilters = computed(() => searchQuery.value || selectedCategory.value || selectedProvince.value)

const applyFilters = () => {
  router.get(
    '/events',
    {
      search: searchQuery.value || undefined,
      category: selectedCategory.value || undefined,
      province: selectedProvince.value || undefined,
    },
    { preserveScroll: true }
  )
  showFilters.value = false
}

const clearFilters = () => {
  searchQuery.value = ''
  selectedCategory.value = ''
  selectedProvince.value = ''
  router.get('/events', {}, { preserveScroll: true })
}

const goToPage = (page: number) => {
  router.get(
    '/events',
    {
      page,
      search: searchQuery.value || undefined,
      category: selectedCategory.value || undefined,
      province: selectedProvince.value || undefined,
    },
    { preserveScroll: true }
  )
}

const getAvailability = (event: Event) => {
  if (event.isFull) return { text: 'Full', color: 'error' }
  const available = event.capacity - event.registeredCount
  if (available <= 5) return { text: `${available} left`, color: 'warning' }
  return { text: `${available} available`, color: 'success' }
}

const pages = computed(() => {
  const total = props.events.meta.last_page
  const current = props.events.meta.current_page
  const delta = 2
  const result: (number | string)[] = []

  if (current > 1 + delta) {
    result.push(1)
    if (current > 2 + delta) result.push('...')
  }

  for (let i = Math.max(1, current - delta); i <= Math.min(total, current + delta); i++) {
    result.push(i)
  }

  if (current < total - delta) {
    if (current < total - 1 - delta) result.push('...')
    result.push(total)
  }

  return result
})
</script>

<template>
  <Head title="Events" />

  <AppLayout layout="full">
    <!-- Hero Section -->
    <div
      class="bg-gradient-to-r from-primary-600 to-primary-800 text-white py-12 md:py-16"
      v-motion
      :initial="{ opacity: 0, y: -20 }"
      :enter="{ opacity: 1, y: 0, transition: { duration: 500 } }"
    >
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <h1 class="text-4xl md:text-5xl font-bold mb-4">Discover Events</h1>
        <p class="text-white/90 text-lg">Explore amazing events happening near you</p>
      </div>
    </div>

    <!-- Main Content -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <!-- Filters Section -->
      <div class="mb-8">
        <!-- Mobile Filter Toggle -->
        <div class="md:hidden mb-4">
          <Button
            variant="outline"
            size="sm"
            @click="showFilters = !showFilters"
            :icon-right="showFilters ? XMarkIcon : AdjustmentsHorizontalIcon"
            full-width
          >
            {{ showFilters ? 'Hide Filters' : 'Show Filters' }}
          </Button>
        </div>

        <!-- Filter Panel -->
        <div
          :class="[
            'grid grid-cols-1 md:grid-cols-4 gap-4 p-6 bg-white rounded-xl border border-neutral-200',
            !showFilters && 'hidden md:grid',
          ]"
          v-motion
          :initial="{ opacity: 0, y: -10 }"
          :enter="{ opacity: 1, y: 0, transition: { duration: 300, delay: 100 } }"
        >
          <Input
            v-model="searchQuery"
            type="text"
            placeholder="Search events..."
            :icon="MagnifyingGlassIcon"
            @keyup.enter="applyFilters"
          />

          <Select
            v-model="selectedCategory"
            placeholder="All Categories"
            :options="categoryOptions"
            searchable
          />

          <Select
            v-model="selectedProvince"
            placeholder="All Provinces"
            :options="provinceOptions"
            searchable
          />

          <div class="flex gap-2 col-span-1 md:col-span-1">
            <Button variant="primary" @click="applyFilters" class="flex-1">
              Filter
            </Button>
            <Button
              v-if="hasActiveFilters"
              variant="outline"
              @click="clearFilters"
              class="flex-1"
            >
              Clear
            </Button>
          </div>
        </div>

        <!-- Active Filters Badge -->
        <div
          v-if="hasActiveFilters"
          class="mt-4 flex flex-wrap gap-2"
          v-motion
          :initial="{ opacity: 0 }"
          :enter="{ opacity: 1, transition: { delay: 150 } }"
        >
          <Badge
            v-if="searchQuery"
            variant="primary"
            rounded
            dot
          >
            Search: {{ searchQuery }}
          </Badge>
          <Badge
            v-if="selectedCategory"
            variant="primary"
            rounded
            dot
          >
            {{ selectedCategory }}
          </Badge>
          <Badge
            v-if="selectedProvince"
            variant="primary"
            rounded
            dot
          >
            {{ selectedProvince }}
          </Badge>
        </div>
      </div>

      <!-- Results Info -->
      <div class="flex justify-between items-center mb-6">
        <p class="text-neutral-600">
          Showing <span class="font-semibold text-neutral-900">{{ props.events.data.length }}</span>
          of
          <span class="font-semibold text-neutral-900">{{ props.events.meta.total }}</span>
          events
        </p>
      </div>

      <!-- Events Grid -->
      <div
        v-if="props.events.data.length > 0"
        class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12"
      >
        <Link
          v-for="(event, index) in props.events.data"
          :key="event.id"
          :href="`/events/${event.id}`"
          class="group"
          v-motion
          :initial="{ opacity: 0, y: 20 }"
          :enter="{
            opacity: 1,
            y: 0,
            transition: { duration: 400, delay: Math.min(index * 50, 300) },
          }"
        >
          <Card hoverable class="h-full flex flex-col overflow-hidden">
            <!-- Image -->
            <div class="relative h-48 overflow-hidden bg-gradient-to-br from-primary-100 to-primary-200">
              <Image
                :src="event.imageUrl as string | undefined"
                :alt="event.name"
                aspect-ratio="16/9"
                class="group-hover:scale-105 transition-transform duration-300"
              />
              <!-- Category Badge -->
              <Badge
                variant="secondary"
                size="sm"
                class="absolute top-3 left-3"
              >
                {{ event.category }}
              </Badge>
              <!-- Price Badge -->
              <Badge
                :variant="event.basePrice === 0 ? 'success' : 'primary'"
                size="sm"
                class="absolute top-3 right-3"
              >
                {{ event.basePrice === 0 ? 'Free' : `$${event.basePrice}` }}
              </Badge>
            </div>

            <!-- Content -->
            <div class="flex-1 p-5 flex flex-col">
              <h3 class="text-lg font-bold text-neutral-900 mb-2 group-hover:text-primary-600 transition-colors line-clamp-2">
                {{ event.name }}
              </h3>

              <p class="text-sm text-neutral-600 mb-4 line-clamp-2">
                {{ event.description }}
              </p>

              <!-- Info Grid -->
              <div class="space-y-2 mb-4 text-sm">
                <div class="flex items-center gap-2 text-neutral-600">
                  <CalendarIcon class="w-4 h-4 flex-shrink-0 text-primary-500" />
                  <span>{{ event.startDate }}</span>
                </div>

                <div class="flex items-center gap-2 text-neutral-600">
                  <MapPinIcon class="w-4 h-4 flex-shrink-0 text-primary-500" />
                  <span>{{ event.location }}</span>
                </div>

                <div class="flex items-center gap-2">
                  <UsersIcon class="w-4 h-4 flex-shrink-0 text-primary-500" />
                  <span
                    :class="[
                      'text-sm font-medium',
                      event.isFull ? 'text-error-600' : getAvailability(event).color === 'warning' ? 'text-warning-600' : 'text-success-600',
                    ]"
                  >
                    {{ getAvailability(event).text }}
                  </span>
                </div>
              </div>

              <!-- Progress Bar -->
              <div class="mb-4">
                <div class="h-2 bg-neutral-200 rounded-full overflow-hidden">
                  <div
                    class="h-full bg-gradient-to-r from-primary-500 to-primary-600 transition-all duration-300"
                    :style="{ width: `${Math.min((event.registeredCount / event.capacity) * 100, 100)}%` }"
                  />
                </div>
                <p class="text-xs text-neutral-500 mt-1">
                  {{ event.registeredCount }} / {{ event.capacity }} registered
                </p>
              </div>

              <!-- Status -->
              <div class="pt-4 border-t border-neutral-200">
                <Badge
                  :variant="event.canRegister ? 'success' : event.isFull ? 'error' : 'warning'"
                  size="sm"
                  class="w-full justify-center"
                >
                  {{ event.canRegister ? 'Registration Open' : event.isFull ? 'Full' : 'Closed' }}
                </Badge>
              </div>
            </div>
          </Card>
        </Link>
      </div>

      <!-- Empty State -->
      <div v-else class="text-center py-16">
        <div class="text-6xl mb-4">🔍</div>
        <h3 class="text-2xl font-bold text-neutral-900 mb-2">No Events Found</h3>
        <p class="text-neutral-600 mb-6">Try adjusting your filters to discover more events</p>
        <Button variant="primary" @click="clearFilters">
          Clear Filters
        </Button>
      </div>

      <!-- Pagination -->
      <div
        v-if="props.events.meta.last_page > 1"
        class="flex justify-center items-center gap-2 mt-12"
        v-motion
        :initial="{ opacity: 0, y: 10 }"
        :enter="{ opacity: 1, y: 0, transition: { delay: 200 } }"
      >
        <Button
          v-if="props.events.meta.current_page > 1"
          variant="outline"
          size="sm"
          @click="goToPage(props.events.meta.current_page - 1)"
        >
          Previous
        </Button>

        <div class="flex gap-1">
          <button
            v-for="page in pages"
            :key="page"
            @click="typeof page === 'number' && goToPage(page)"
            :disabled="page === '...'"
            :class="[
              'px-3 py-2 rounded-lg font-medium transition-all',
              page === props.events.meta.current_page
                ? 'bg-primary-600 text-white shadow-md'
                : page === '...'
                  ? 'text-neutral-500 cursor-default'
                  : 'border border-neutral-300 text-neutral-700 hover:border-primary-300 hover:bg-primary-50',
            ]"
          >
            {{ page }}
          </button>
        </div>

        <Button
          v-if="props.events.meta.current_page < props.events.meta.last_page"
          variant="outline"
          size="sm"
          @click="goToPage(props.events.meta.current_page + 1)"
        >
          Next
        </Button>
      </div>
    </div>
  </AppLayout>
</template>

// inertia/pages/events/index.tsx
import { Head, router } from '@inertiajs/react'
import { useState, useMemo } from 'react'
import { motion, AnimatePresence } from 'motion/react'
import {
  MagnifyingGlassIcon,
  FunnelIcon,
  MapPinIcon,
  CalendarIcon,
  UsersIcon,
  TagIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline'
import AppLayout from '~/components/layouts/AppLayout'
import Card from '~/components/ui/Card'
import Button from '~/components/ui/Button'
import Input from '~/components/ui/Input'
import Select from '~/components/ui/Select'
import Badge from '~/components/ui/Badge'
import Image from '~/components/ui/Image'
import Pagination from '~/components/ui/Pagination'
import { useTheme } from '~/hooks/useTheme'
import { formatDate, formatCurrency, truncate } from '~/lib/utils'
import { PROVINCES, EVENT_CATEGORIES } from '~/lib/constants'
import type { PaginatedResponse } from '~/types/common'

interface Event {
  id: number
  name: string
  description: string
  location: string
  province: string
  commune: string
  startDate: string
  endDate: string
  capacity: number
  registeredCount: number
  availableSeats: number
  imageUrl: string | null
  category: string
  basePrice: number
  isFull: boolean
  canRegister: boolean
  isRegistered: boolean
  isUpcoming: boolean
  isOngoing: boolean
  isFinished: boolean
}

interface Props {
  events: PaginatedResponse<Event>
  filters: {
    search?: string
    category?: string
    province?: string
  }
}

export default function EventsIndex({ events, filters }: Props) {
  const { config, getPlaceholder } = useTheme()
  const [showFilters, setShowFilters] = useState(false)
  const [localFilters, setLocalFilters] = useState(filters)

  const categoryOptions = EVENT_CATEGORIES.map((cat) => ({
    value: cat,
    label: cat,
  }))

  const provinceOptions = PROVINCES.map((p) => ({
    value: p,
    label: p,
  }))

  const activeFiltersCount = useMemo(() => {
    let count = 0
    if (localFilters.search) count++
    if (localFilters.category) count++
    if (localFilters.province) count++
    return count
  }, [localFilters])

  const handleSearch = (value: string | number) => {
    setLocalFilters({ ...localFilters, search: value.toString() })
  }

  const handleFilterChange = (key: string, value: any) => {
    setLocalFilters({ ...localFilters, [key]: value })
  }

  const applyFilters = () => {
    router.get('/events', localFilters, {
      preserveState: true,
      preserveScroll: true,
    })
    setShowFilters(false)
  }

  const clearFilters = () => {
    setLocalFilters({ search: '', category: '', province: '' })
    router.get(
      '/events',
      {},
      {
        preserveState: true,
        preserveScroll: true,
      }
    )
    setShowFilters(false)
  }

  const handlePageChange = (page: number) => {
    router.get(
      '/events',
      { ...localFilters, page },
      {
        preserveState: true,
        preserveScroll: false,
      }
    )
  }

  const getEventStatusBadge = (event: Event) => {
    if (event.isOngoing) {
      return (
        <Badge variant="info" dot pulse>
          En cours
        </Badge>
      )
    }
    if (event.isUpcoming) {
      return (
        <Badge variant="success" dot>
          À venir
        </Badge>
      )
    }
    if (event.isFinished) {
      return <Badge variant="neutral">Terminé</Badge>
    }
    return null
  }

  return (
    <>
      <Head title="Événements" />
      <AppLayout>
        {/* Hero Section */}
        <section className="relative bg-linear-to-br from-primary-600 via-primary-700 to-secondary-600 text-white py-16 -mt-8 mb-8">
          <div className="absolute inset-0 bg-[url('/images/pattern.svg')] opacity-10" />
          <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <h1 className="text-4xl md:text-5xl font-bold mb-4">Découvrez nos événements</h1>
              <p className="text-xl text-white/90 mb-8 max-w-2xl">
                Explorez une sélection d'événements passionnants près de chez vous
              </p>

              {/* Search Bar */}
              <div className="max-w-2xl">
                <div className="relative">
                  <Input
                    value={localFilters.search || ''}
                    onChange={handleSearch}
                    placeholder="Rechercher un événement..."
                    icon={MagnifyingGlassIcon}
                    size="lg"
                    onKeyDown={(e: React.KeyboardEvent) => {
                      if (e.key === 'Enter') applyFilters()
                    }}
                  />
                  <Button
                    variant="primary"
                    size="lg"
                    className="absolute right-2 top-1/2 -translate-y-1/2"
                    onClick={applyFilters}
                  >
                    Rechercher
                  </Button>
                </div>
              </div>
            </motion.div>
          </div>
        </section>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {/* Filters Bar */}
          <motion.div
            className="flex items-center justify-between mb-8 flex-wrap gap-4"
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: 0.2 }}
          >
            <div className="flex items-center gap-4">
              <Button
                variant="outline"
                iconLeft={FunnelIcon}
                onClick={() => setShowFilters(!showFilters)}
              >
                Filtres
                {activeFiltersCount > 0 && (
                  <Badge variant="primary" size="sm" rounded>
                    {activeFiltersCount}
                  </Badge>
                )}
              </Button>

              {activeFiltersCount > 0 && (
                <Button variant="ghost" size="sm" iconLeft={XMarkIcon} onClick={clearFilters}>
                  Réinitialiser
                </Button>
              )}
            </div>

            <p className="text-sm text-neutral-600">
              {events.meta.total} événement{events.meta.total > 1 ? 's' : ''} trouvé
              {events.meta.total > 1 ? 's' : ''}
            </p>
          </motion.div>

          {/* Filters Panel */}
          <AnimatePresence>
            {showFilters && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: 'auto' }}
                exit={{ opacity: 0, height: 0 }}
                transition={{ duration: 0.3 }}
                className="mb-8 overflow-hidden"
              >
                <Card variant="bordered" padding="lg">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <Select
                      label="Catégorie"
                      value={localFilters.category || ''}
                      onChange={(value) => handleFilterChange('category', value)}
                      options={categoryOptions}
                      placeholder="Toutes les catégories"
                      searchable
                    />
                    <Select
                      label="Wilaya"
                      value={localFilters.province || ''}
                      onChange={(value) => handleFilterChange('province', value)}
                      options={provinceOptions}
                      placeholder="Toutes les wilayas"
                      searchable
                    />
                  </div>

                  <div className="flex justify-end gap-3 mt-6">
                    <Button variant="ghost" onClick={() => setShowFilters(false)}>
                      Annuler
                    </Button>
                    <Button variant="primary" onClick={applyFilters}>
                      Appliquer les filtres
                    </Button>
                  </div>
                </Card>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Events Grid */}
          {events.data.length === 0 ? (
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              className="text-center py-16"
            >
              <div className="text-6xl mb-4">🔍</div>
              <h3 className="text-2xl font-bold text-neutral-900 mb-2">Aucun événement trouvé</h3>
              <p className="text-neutral-600 mb-6">Essayez d'ajuster vos critères de recherche</p>
              <Button variant="primary" onClick={clearFilters}>
                Voir tous les événements
              </Button>
            </motion.div>
          ) : (
            <>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {events.data.map((event, index) => (
                  <motion.div
                    key={event.id}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.4, delay: index * 0.05 }}
                  >
                    <Card hoverable clickable className="h-full flex flex-col">
                      <div className="relative">
                        <Image
                          src={event.imageUrl || getPlaceholder('event')}
                          alt={event.name}
                          aspectRatio="16/9"
                          rounded="lg"
                        />
                        <div className="absolute top-3 right-3">{getEventStatusBadge(event)}</div>
                        {event.isRegistered && (
                          <div className="absolute top-3 left-3">
                            <Badge variant="success">Inscrit</Badge>
                          </div>
                        )}
                      </div>

                      <div className="flex-1 flex flex-col mt-4">
                        <div className="flex items-start justify-between gap-2 mb-3">
                          <h3 className="text-lg font-bold text-neutral-900 line-clamp-2">
                            {event.name}
                          </h3>
                          <Badge variant="primary" size="sm">
                            {event.category}
                          </Badge>
                        </div>

                        <p className="text-sm text-neutral-600 mb-4 line-clamp-2">
                          {truncate(event.description, 100)}
                        </p>

                        <div className="space-y-2 mb-4">
                          <div className="flex items-center gap-2 text-sm text-neutral-700">
                            <CalendarIcon className="w-4 h-4 text-primary-600" />
                            <span>{formatDate(event.startDate)}</span>
                          </div>
                          <div className="flex items-center gap-2 text-sm text-neutral-700">
                            <MapPinIcon className="w-4 h-4 text-primary-600" />
                            <span>
                              {event.commune}, {event.province}
                            </span>
                          </div>
                          <div className="flex items-center gap-2 text-sm text-neutral-700">
                            <UsersIcon className="w-4 h-4 text-primary-600" />
                            <span>
                              {event.availableSeats} place{event.availableSeats > 1 ? 's' : ''}{' '}
                              disponible{event.availableSeats > 1 ? 's' : ''}
                            </span>
                          </div>
                        </div>

                        <div className="mt-auto pt-4 border-t border-neutral-200 flex items-center justify-between">
                          <div>
                            {event.basePrice > 0 ? (
                              <p className="text-lg font-bold text-primary-600">
                                {formatCurrency(event.basePrice)}
                              </p>
                            ) : (
                              <Badge variant="success">Gratuit</Badge>
                            )}
                          </div>
                          <Button variant="primary" size="sm" href={`/events/${event.id}`}>
                            Détails
                          </Button>
                        </div>
                      </div>
                    </Card>
                  </motion.div>
                ))}
              </div>

              {/* Pagination */}
              {events.meta.last_page > 1 && (
                <motion.div
                  className="mt-12"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ delay: 0.4 }}
                >
                  <Pagination
                    currentPage={events.meta.current_page}
                    lastPage={events.meta.last_page}
                    totalItems={events.meta.total}
                    itemsPerPage={events.meta.per_page}
                    onChangePage={handlePageChange}
                  />
                </motion.div>
              )}
            </>
          )}
        </div>
      </AppLayout>
    </>
  )
}
