// inertia/components/layouts/AppLayout.tsx
import { usePage } from '@inertiajs/react'
import { motion } from 'motion/react'
import Header from '~/components/shared/Header'
import Footer from '~/components/shared/Footer'
import FlashMessage from '~/components/shared/FlashMessage'

interface AppLayoutProps {
  children: React.ReactNode
  showHeader?: boolean
  showFooter?: boolean
  containerClass?: string
  layout?: 'default' | 'auth' | 'full'
}

export default function AppLayout({
  children,
  showHeader = true,
  showFooter = true,
  containerClass = 'max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8',
  layout = 'default',
}: AppLayoutProps) {
  const { props } = usePage()
  const auth = props.auth as { user?: any } | undefined

  return (
    <div className="min-h-screen bg-neutral-50 flex flex-col antialiased">
      {showHeader && <Header user={auth?.user} />}
      <FlashMessage />

      <motion.main
        className="flex-1"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.3, delay: 0.1 }}
      >
        {layout === 'full' ? (
          <div className="w-full">{children}</div>
        ) : (
          <div className={containerClass}>{children}</div>
        )}
      </motion.main>

      {showFooter && <Footer />}
    </div>
  )
}

// inertia/components/layouts/AppLayout.vue
<script setup lang="ts">
import { computed } from 'vue'
import { usePage } from '@inertiajs/vue3'
import AppHeader from '@/components/shared/Header.vue'
import AppFooter from '@/components/shared/Footer.vue'
import FlashMessages from '@/components/shared/FlashMessage.vue'

interface Props {
  showHeader?: boolean
  showFooter?: boolean
  containerClass?: string
}

withDefaults(defineProps<Props>(), {
  showHeader: true,
  showFooter: true,
  containerClass: '',
})

const page = usePage()
const auth = computed(() => page.props.auth as { user?: any } | undefined)
</script>

<template>
  <div class="min-h-screen bg-neutral-50 flex flex-col antialiased">
    <AppHeader v-if="showHeader" :user="auth?.user" />
    <FlashMessages />

    <main
      class="flex-1"
      v-motion
      :initial="{ opacity: 0 }"
      :enter="{ opacity: 1, transition: { duration: 300, delay: 100 } }"
    >
      <div :class="containerClass">
        <slot />
      </div>
    </main>

    <AppFooter v-if="showFooter" />
  </div>
</template>
