// inertia/components/layouts/AuthLayout.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { usePage } from '@inertiajs/vue3'
import Alert from '#ui/Alert.vue'
import config from '~/theme.config.json'
import { motion } from 'motion-v'

interface FlashMessages {
  success?: string
  error?: string
  info?: string
  warning?: string
}

const page = usePage()
const dismissedFlash = ref<Set<string>>(new Set())

const flash = computed<FlashMessages>(() => {
  const props = page.props as any
  return {
    success: props.flash?.success,
    error: props.flash?.error,
    info: props.flash?.info,
    warning: props.flash?.warning,
  }
})

const visibleFlash = computed(() => {
  const visible: Record<string, string> = {}
  const entries = Object.entries(flash.value) as [keyof FlashMessages, string | undefined][]

  entries.forEach(([key, value]) => {
    if (value && !dismissedFlash.value.has(key)) {
      visible[key] = value
    }
  })
  return visible
})

const dismissFlash = (type: string) => {
  dismissedFlash.value.add(type)
}
</script>

<template>
  <div
    class="min-h-screen bg-gradient-to-br from-primary-50 via-white to-primary-100 flex flex-col relative overflow-hidden">
    <!-- Animated Background Elements -->
    <div class="absolute inset-0 overflow-hidden pointer-events-none">
      <motion.div class="absolute -top-40 -right-40 w-80 h-80 bg-primary-200/30 rounded-full blur-3xl"
        :initial="{ scale: 0, opacity: 0 }"
        :enter="{ scale: 1, opacity: 1, transition: { duration: 1000, ease: 'easeOut' } }" />
      <motion.div class="absolute -bottom-40 -left-40 w-96 h-96 bg-secondary-200/30 rounded-full blur-3xl"
        :initial="{ scale: 0, opacity: 0 }" :enter="{
          scale: 1,
          opacity: 1,
          transition: { duration: 1000, delay: 200, ease: 'easeOut' },
        }" />
    </div>

    <!-- Header with Logo -->
    <motion.header class="relative py-6 px-4" :initial="{ y: -20, opacity: 0 }"
      :enter="{ y: 0, opacity: 1, transition: { duration: 400 } }">
      <div class="max-w-7xl mx-auto">
        <a href="/" class="inline-flex items-center gap-3 group">
          <motion.div
            class="w-12 h-12 bg-gradient-to-br from-primary-600 to-primary-700 rounded-xl flex items-center justify-center shadow-lg group-hover:shadow-xl transition-all duration-300 group-hover:scale-105"
            :initial="{ rotate: -180, scale: 0 }" :enter="{
              rotate: 0,
              scale: 1,
              transition: { type: 'spring', stiffness: 200, delay: 100 },
            }">
            <span class="text-xl font-bold text-white">{{ config.branding.logo.icon }}</span>
          </motion.div>
          <span class="text-xl font-bold text-neutral-900 group-hover:text-primary-600 transition-colors duration-300">
            {{ config.branding.logo.text }}
          </span>
        </a>
      </div>
    </motion.header>

    <!-- Flash Messages -->
    <div v-if="Object.keys(visibleFlash).length" class="relative px-4 pb-4">
      <div class="max-w-md mx-auto space-y-2">
        <Alert v-for="(message, type) in visibleFlash" :key="type" :type="type as any" dismissible
          @dismiss="dismissFlash(type)">
          {{ message }}
        </Alert>
      </div>
    </div>

    <!-- Main Content -->
    <main class="relative flex-1 flex items-center justify-center px-4 py-8">
      <slot />
    </main>

    <!-- Footer -->
    <motion.footer class="relative py-6 text-center text-sm text-neutral-600" :initial="{ y: 20, opacity: 0 }"
      :enter="{ y: 0, opacity: 1, transition: { duration: 400, delay: 200 } }">
      <p>
        &copy; {{ new Date().getFullYear() }} {{ config.branding.logo.text }}. Tous droits réservés.
      </p>
    </motion.footer>
  </div>
</template>

// inertia/components/layouts/AuthLayout.tsx
import { usePage, Link } from '@inertiajs/react'
import { motion } from 'framer-motion'
import { useState } from 'react'
import Alert from '~/components/ui/Alert'
import { use_theme } from '~/composables/use_theme'

interface FlashMessages {
  success?: string
  error?: string
  info?: string
  warning?: string
}

interface AuthLayoutProps {
  children: React.ReactNode
}

export default function AuthLayout({ children }: AuthLayoutProps) {
  const { props } = usePage()
  const { config } = use_theme()
  const [dismissedFlash, setDismissedFlash] = useState<Set<string>>(new Set())

  const flash = props.flash as FlashMessages | undefined

  const visibleFlash = flash
    ? Object.entries(flash).filter(
        ([key, value]) => value && !dismissedFlash.has(key)
      )
    : []

  const dismissFlash = (type: string) => {
    setDismissedFlash((prev) => new Set([...prev, type]))
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-50 via-white to-primary-100 flex flex-col relative overflow-hidden">
      {/* Animated Background Elements */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <motion.div
          className="absolute -top-40 -right-40 w-80 h-80 bg-primary-200/30 rounded-full blur-3xl"
          initial={{ scale: 0, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          transition={{ duration: 1, ease: 'easeOut' }}
        />
        <motion.div
          className="absolute -bottom-40 -left-40 w-96 h-96 bg-secondary-200/30 rounded-full blur-3xl"
          initial={{ scale: 0, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          transition={{ duration: 1, delay: 0.2, ease: 'easeOut' }}
        />
      </div>

      {/* Header with Logo */}
      <motion.header
        className="relative py-6 px-4"
        initial={{ y: -20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ duration: 0.4 }}
      >
        <div className="max-w-7xl mx-auto">
          <Link href="/" className="inline-flex items-center gap-3 group">
            <motion.div
              className="w-12 h-12 bg-gradient-to-br from-primary-600 to-primary-700 rounded-xl flex items-center justify-center shadow-lg group-hover:shadow-xl transition-all duration-300 group-hover:scale-105"
              initial={{ rotate: -180, scale: 0 }}
              animate={{ rotate: 0, scale: 1 }}
              transition={{ type: 'spring', stiffness: 200, delay: 0.1 }}
            >
              <span className="text-xl font-bold text-white">
                {config.branding.logo.icon}
              </span>
            </motion.div>
            <span className="text-xl font-bold text-neutral-900 group-hover:text-primary-600 transition-colors duration-300">
              {config.branding.logo.text}
            </span>
          </Link>
        </div>
      </motion.header>

      {/* Flash Messages */}
      {visibleFlash.length > 0 && (
        <div className="relative px-4 pb-4">
          <div className="max-w-md mx-auto space-y-2">
            {visibleFlash.map(([type, message]) => (
              <Alert
                key={type}
                type={type as any}
                dismissible
                onDismiss={() => dismissFlash(type)}
              >
                {message}
              </Alert>
            ))}
          </div>
        </div>
      )}

      {/* Main Content */}
      <main className="relative flex-1 flex items-center justify-center px-4 py-8">
        {children}
      </main>

      {/* Footer */}
      <motion.footer
        className="relative py-6 text-center text-sm text-neutral-600"
        initial={{ y: 20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ duration: 0.4, delay: 0.2 }}
      >
        <p>
          &copy; {new Date().getFullYear()} {config.branding.logo.text}. Tous
          droits réservés.
        </p>
      </motion.footer>
    </div>
  )
}
